### ISSUE TITLE
Add KML integration testing with sample files

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#13]
Example files that pass are here: http://cite.opengeospatial.org/teamengine/about/kml22/2.2/site/Supporting_Docs_KML_2.2_GDAL.zip

The kml sample file from the start up web form should fail, as follows:
https://developers.google.com/kml/documentation/KML_Samples.kml

======== Test groups ========
Conformance Level 1
   Passed: 41 | Failed: 1 | Skipped: 0
Conformance Level 2
   Passed: 0 | Failed: 0 | Skipped: 27
Conformance Level 3
   Passed: 0 | Failed: 0 | Skipped: 1

**Comment by bermud** [comment]
Is the script testing that conformance level 1 fails 1?

**Comment by keshavnangare** [comment]
I have updated the kml jmeter script which will test the kml22 test-suite is failing at conformance level 1 or not with test 1 fail.

If this condition is true then the integration testing script will show the result like "Test completed as expected (FAILED)" otherwise it will show "Test completed as expected (PASSED)".

This changes are fixed with this commit 248da846e952849164b7ec0ab6db781f74086f8f

**Comment by keshavnangare** [comment]
I have updated the integration result, this result is parsed from the REST API response.
What is failing in the gml32 test, that will appear in to final result.

Sample result:
![integaration_testing result](https://cloud.githubusercontent.com/assets/14732650/13497211/36a18320-e17a-11e5-8023-a8cf692da4d1.png)

**Comment by bermud** [comment]
Great!
