### ISSUE TITLE
Improve report capturing the information about the system

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#6]
## Motivation

We should be able to capture the installation in different environments, either creating a script for each environment or installing TE and passing the information of that environment in a properties file or similar.
## The report should look like the following:

TE integration testing - 2015/09/29 15:58:05

OS
- Linux cite 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64
- Java
  - java version "1.7.0_80"
  - Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
  - Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- apache-tomcat-7.0.47
- jmeter

TE version 
- TEAM Engine 4.3-SNAPSHOT
- commit 0a054f1cf8ff28437981c9c24e29fdb9e392e13a)

Default Build
- Default build : SUCCESS
- User can be created and logins : SUCCESS

Test Name : CSW 2.0.2 revision 1.14
- Test can be run : SUCCESS
- Test run finishes successfully : SUCCESS
- Test completed as expected (PASSED) : SUCCESS

Test Name : GML 3.2.1 revision 1.21
- Test can be run : SUCCESS
- Test run finishes successfully : SUCCESS
- Test completed as expected (FAILED) : SUCCESS

Test Name : SOS 1.0.0 revision 1.13
- Test can be run : SUCCESS
- Test run finishes successfully : SUCCESS

**Comment by keshavnangare** [comment]
- I have updated the jmeter which will check the test result is failed or passed (It is done for only GML32).
- I have added the response assertion to check the test result.
- Also updated the shell-script to update the integration testing result.
- Depend on that assertion result, the final result get updated.

Fixed with this commit  64ae5be2e433bc2cc718470459397efd265fbfe7
